name: deploy

on:
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env: 
  DOTNET_VERSION: '10.0.103'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    name: "job build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Dotnet publish
        run: dotnet publish MiProyectoMVC/MiProyectoMVC.csproj --configuration ${{ env.BUILD_CONFIGURATION }} -o artifacts
    
      - name : Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uv-artifacts
          path: artifacts/

  deploy:
    name: "job deploy"
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: download artifacts
        uses: actions/checkout@v4
        with: 
          name: uv-artifacts
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENTE_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Deploy to Azure Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-api-uv-lixba-examen
          package: artifacts/